import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./ui/globals.css";

import "react-toastify/dist/ReactToastify.css";
import SomethingProvider from "./ui/somethingProvider";
import { auth } from "@/auth";
import Header from "@/app/ui/header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// export const LayoutContext = createContext<{
//   setState: Dispatch<SetStateAction<Session | null>>
//   state: Session | null
// }>

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();

  return (
    <html lang="en">
      <body className={inter.className}>
        <SomethingProvider session={session}>
          <Header />
          {children}
        </SomethingProvider>
      </body>
    </html>
  );
}
